version: "3.9"
services:
  app:
    container_name: BadBank
    restart: always
    build: .
    ports: 
      - '3000:3000'
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'